---
abstract: 'Extends Facebook::Graph to create and save an access token.'
author:
  - 'Andrew Grangaard <spazm@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Facebook-Graph-Cmdline
requires:
  Any::Moose: 0
  Facebook::Graph: 0
  HTTP::Daemon: 6.00
  MooseX::Getopt: 0
  MooseX::SimpleConfig: 0
  MouseX::Getopt: 0
  MouseX::SimpleConfig: 0
  URI: 0
  YAML::Any: 0
  perl: v5.10
resources:
  homepage: http://lowlevelmanager.com/
  repository: http://github.com/spazm/p5-facebook-graph-cmdline.git
version: 0.123460
